# MongoDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: todo-lab
  labels:
    app: mongodb
    env: dev
type: Opaque
data:
  username: YWRtaW4=                  # admin
  password: cGFzc3dvcmQxMjM=          # password123
