# MongoDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: dev
type: Opaque
data:
  username: YWRtaW4=                    # admin
  password: cGFzc3dvcmQxMjM=            # password123
